// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autoscaler/ContainerMetric.proto

/*
Package autoscaler is a generated protocol buffer package.

It is generated from these files:
	autoscaler/ContainerMetric.proto
	autoscaler/LogMessage.proto

It has these top-level messages:
	ProtoContainerMetric
	ProtoLogMessage
*/
package autoscaler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoContainerMetric struct {
	Timestamp        int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MetricName       string `protobuf:"bytes,2,opt,name=metricName" json:"metricName,omitempty"`
	AppId            string `protobuf:"bytes,3,opt,name=appId" json:"appId,omitempty"`
	AppName          string `protobuf:"bytes,4,opt,name=appName" json:"appName,omitempty"`
	Space            string `protobuf:"bytes,5,opt,name=space" json:"space,omitempty"`
	OrganizationGuid string `protobuf:"bytes,6,opt,name=organization_guid,json=organizationGuid" json:"organization_guid,omitempty"`
	Cpu              int32  `protobuf:"varint,7,opt,name=cpu" json:"cpu,omitempty"`
	Ram              int64  `protobuf:"varint,8,opt,name=ram" json:"ram,omitempty"`
	InstanceIndex    int32  `protobuf:"varint,9,opt,name=instanceIndex" json:"instanceIndex,omitempty"`
	Description      string `protobuf:"bytes,10,opt,name=description" json:"description,omitempty"`
}

func (m *ProtoContainerMetric) Reset()                    { *m = ProtoContainerMetric{} }
func (m *ProtoContainerMetric) String() string            { return proto.CompactTextString(m) }
func (*ProtoContainerMetric) ProtoMessage()               {}
func (*ProtoContainerMetric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoContainerMetric) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProtoContainerMetric) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *ProtoContainerMetric) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ProtoContainerMetric) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ProtoContainerMetric) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *ProtoContainerMetric) GetOrganizationGuid() string {
	if m != nil {
		return m.OrganizationGuid
	}
	return ""
}

func (m *ProtoContainerMetric) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ProtoContainerMetric) GetRam() int64 {
	if m != nil {
		return m.Ram
	}
	return 0
}

func (m *ProtoContainerMetric) GetInstanceIndex() int32 {
	if m != nil {
		return m.InstanceIndex
	}
	return 0
}

func (m *ProtoContainerMetric) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*ProtoContainerMetric)(nil), "autoscaler.ProtoContainerMetric")
}

func init() { proto.RegisterFile("autoscaler/ContainerMetric.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4b, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xe9, 0x69, 0x7b, 0xc6, 0x2e, 0x11, 0xc6, 0x30, 0x8b, 0x5a, 0x88, 0x04, 0x71, 0xd1,
	0x20, 0xe8, 0xc2, 0x23, 0xb8, 0x90, 0x59, 0x28, 0xd2, 0x17, 0x90, 0x32, 0x09, 0x43, 0xc0, 0x3c,
	0x48, 0xd2, 0x20, 0x5e, 0xcb, 0x0b, 0x4a, 0x6a, 0x90, 0x6e, 0xdd, 0xd5, 0xff, 0xfd, 0x5f, 0x1e,
	0x14, 0x48, 0x9a, 0x4a, 0xc8, 0x8a, 0x3e, 0x4c, 0xba, 0x7f, 0x0c, 0xbe, 0x90, 0xf5, 0x26, 0x3d,
	0x9b, 0x92, 0xac, 0xba, 0x8b, 0x29, 0x94, 0x20, 0x60, 0x36, 0xae, 0xbf, 0x57, 0xb0, 0x7b, 0xad,
	0xf4, 0x9f, 0x2a, 0x2e, 0xa1, 0x2f, 0xd6, 0x99, 0x5c, 0xc8, 0x45, 0x6c, 0x64, 0x33, 0xb4, 0xe3,
	0x0c, 0xc4, 0x15, 0x80, 0x63, 0xef, 0x85, 0x9c, 0xc1, 0x95, 0x6c, 0x86, 0x7e, 0x5c, 0x10, 0xb1,
	0x83, 0x8e, 0x62, 0xdc, 0x6b, 0x6c, 0xb9, 0x3a, 0x06, 0x81, 0xb0, 0xa1, 0x18, 0xf9, 0xc8, 0x09,
	0xf3, 0xdf, 0x58, 0xfd, 0x1c, 0x49, 0x19, 0xec, 0x8e, 0x3e, 0x07, 0x71, 0x0b, 0x17, 0x21, 0x1d,
	0xc8, 0xdb, 0x2f, 0x2a, 0x36, 0xf8, 0xb7, 0xc3, 0x64, 0x35, 0xae, 0xd9, 0xd8, 0x2e, 0x8b, 0xa7,
	0xc9, 0x6a, 0xb1, 0x85, 0x56, 0xc5, 0x09, 0x37, 0xb2, 0x19, 0xba, 0xb1, 0x8e, 0x95, 0x24, 0x72,
	0x78, 0xca, 0x9f, 0xaf, 0xa3, 0xb8, 0x81, 0x73, 0xeb, 0x73, 0x21, 0xaf, 0xcc, 0xde, 0x6b, 0xf3,
	0x89, 0x3d, 0xdb, 0x7f, 0xa1, 0x90, 0x70, 0xa6, 0x4d, 0x56, 0xc9, 0xc6, 0x7a, 0x39, 0x02, 0x3f,
	0xb8, 0x44, 0xef, 0x6b, 0x5e, 0xe4, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x71, 0xfc,
	0x6f, 0x6c, 0x01, 0x00, 0x00,
}
