// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LogMessage.proto

/*
Package autoscaler is a generated protocol buffer package.

It is generated from these files:
	LogMessage.proto

It has these top-level messages:
	ProtoLogMessage
*/
package autoscaler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoLogMessage struct {
	Timestamp      int64  `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	LogMessage     string `protobuf:"bytes,2,opt,name=LogMessage" json:"LogMessage,omitempty"`
	LogMessageType string `protobuf:"bytes,3,opt,name=LogMessageType" json:"LogMessageType,omitempty"`
	AppId          string `protobuf:"bytes,4,opt,name=AppId" json:"AppId,omitempty"`
}

func (m *ProtoLogMessage) Reset()                    { *m = ProtoLogMessage{} }
func (m *ProtoLogMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtoLogMessage) ProtoMessage()               {}
func (*ProtoLogMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoLogMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProtoLogMessage) GetLogMessage() string {
	if m != nil {
		return m.LogMessage
	}
	return ""
}

func (m *ProtoLogMessage) GetLogMessageType() string {
	if m != nil {
		return m.LogMessageType
	}
	return ""
}

func (m *ProtoLogMessage) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func init() {
	proto.RegisterType((*ProtoLogMessage)(nil), "autoscaler.ProtoLogMessage")
}

func init() { proto.RegisterFile("LogMessage.proto", fileDescriptor0) }

var fileDescriptor2 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf0, 0xc9, 0x4f, 0xf7,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x2c,
	0x2d, 0xc9, 0x2f, 0x4e, 0x4e, 0xcc, 0x49, 0x2d, 0x52, 0xea, 0x65, 0xe4, 0xe2, 0x0f, 0x00, 0x89,
	0x22, 0x54, 0x09, 0xc9, 0x70, 0x71, 0x86, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x21, 0x04, 0x84, 0xe4, 0xb8, 0xb8, 0x10, 0x6a, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x84, 0xd4, 0xb8, 0xf8, 0x10, 0xbc, 0x90, 0xca, 0x82,
	0x54, 0x09, 0x66, 0xb0, 0x1a, 0x34, 0x51, 0x21, 0x11, 0x2e, 0x56, 0xc7, 0x82, 0x02, 0xcf, 0x14,
	0x09, 0x16, 0xb0, 0x34, 0x84, 0x93, 0xc4, 0x06, 0x76, 0xa2, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x47, 0xe0, 0xd2, 0x3e, 0xb6, 0x00, 0x00, 0x00,
}
