subscription_id: <subscription_id>
insecure_ssl_skip_verify: true

http:
  baseurls:
  - http://baseurl1
  - http://baseurl2
  endpoints:
    - endpoint: serverconfig
      interval: 3600
    - endpoint: datadomain
      interval: 60

kafka:
  hosts:
  - 127.0.0.1
  port: 9093
  retry_max: 10
  retry_backoff_ms: 500
  secure: true
  sasl:
    username: <username>
    password: <password>
  ssl:
    ca: |
      <ca_cert>